import type { Metadata } from "next";
import { LegalShell } from "@/components/site/legal-shell";
import { TERMS_LAST_UPDATED } from "@/lib/legal/terms-version";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How AllInfratech collects, uses, and protects personal data.",
  alternates: { canonical: "/legal/privacy" },
};

const h2 = "mt-10 mb-3 font-heading text-[24px] leading-tight text-[var(--color-ink)] md:text-[26px]";
const h3 = "mt-6 mb-2 font-heading text-[20px] leading-tight text-[var(--color-ink)]";
const ul = "list-disc space-y-2 pl-6";

export default function PrivacyPage() {
  return (
    <LegalShell title="Privacy Policy" updated={TERMS_LAST_UPDATED}>
      <p className="text-[16px] text-[var(--color-ink-3)]">
        AllInfratech &mdash; Privacy Policy. Effective date: {TERMS_LAST_UPDATED}. Version 1.0.
      </p>

      <p>
        This Privacy Policy explains how Resolute Management Consultancy
        (&ldquo;Resolute&rdquo;, &ldquo;we&rdquo;) collects, uses, and protects
        personal data in connection with AllInfratech (the
        &ldquo;Directory&rdquo;), available at{" "}
        <strong>allinfratech.com</strong>. We are the controller of the
        personal data described below and are contactable at{" "}
        <strong>team@allinfratech.com</strong>.
      </p>

      <h2 className={h2}>1. The data we collect</h2>

      <h3 className={h3}>(a) Visitors (anyone browsing the site)</h3>
      <ul className={ul}>
        <li><strong>Aggregate analytics</strong> via Plausible Analytics. Plausible is a privacy-friendly product that does not use cookies, does not collect personal identifiers, and does not track visitors across sites. We see counts (page views, referrers, country, browser, device type) in aggregate &mdash; not individuals.</li>
        <li><strong>Server logs</strong> generated by our hosting provider (Vercel) and our database provider (Neon). These contain IP address, request path, status code, user-agent, and timestamps, retained for a short period for security, abuse-prevention, and debugging purposes.</li>
        <li><strong>Form submissions</strong> if you choose to use the &ldquo;Contact this vendor&rdquo;, &ldquo;Suggest an app&rdquo;, or general contact form. We collect the data you enter (typically name, email, message) and the IP address the request came from for rate-limiting and abuse-prevention.</li>
      </ul>
      <p>
        No advertising cookies, no cross-site trackers, no fingerprinting.
      </p>

      <h3 className={h3}>(b) Vendors (signed-in users managing a listing)</h3>
      <ul className={ul}>
        <li><strong>Account profile from Clerk</strong> when you sign in via LinkedIn OAuth: your name, email address, LinkedIn profile URL, and a stable user identifier issued by Clerk. We do not see your LinkedIn password.</li>
        <li><strong>Vendor record</strong>: the company you represent, your role at the company, the listing(s) you manage, and any company-related fields you submit through the dashboard.</li>
        <li><strong>Legal-acceptance audit trail</strong>: when you accept these terms (or a future updated version), we record the version accepted, timestamp, IP address, and user-agent string. This evidences your consent and is retained for the life of your account plus a reasonable period thereafter.</li>
        <li><strong>Activity</strong>: records of submissions, edits, and admin-visible actions you take in the dashboard, retained as audit logs.</li>
        <li><strong>Inbound vendor messages</strong>: messages sent to you by Visitors via the &ldquo;Contact this vendor&rdquo; form are stored briefly for moderation and forwarded to the contact email on your account.</li>
      </ul>

      <h3 className={h3}>(c) Administrators (Resolute employees and contractors)</h3>
      <p>
        Account profile (name, work email), audit log of admin actions in the
        admin panel.
      </p>

      <h2 className={h2}>2. Why we use your data (legal bases)</h2>
      <p>
        We rely on the following legal bases under applicable data-protection
        law (including the UAE Personal Data Protection Law and the EU/UK GDPR
        where it applies):
      </p>
      <ul className={ul}>
        <li><strong>Contract</strong> &mdash; to operate vendor accounts and provide the dashboard you have signed up for.</li>
        <li><strong>Legitimate interests</strong> &mdash; to operate, secure, and improve the Directory; to prevent abuse and fraud; to maintain audit logs; to forward Visitor messages to the relevant Vendor; to keep aggregate analytics about how the Directory is used.</li>
        <li><strong>Legal obligation</strong> &mdash; to retain records we are required to keep, and to respond to lawful requests from authorities.</li>
        <li><strong>Consent</strong> &mdash; where you have actively opted in (for example, accepting these terms during onboarding).</li>
      </ul>

      <h2 className={h2}>3. How long we keep your data</h2>
      <ul className={ul}>
        <li><strong>Visitor analytics</strong>: aggregate data only; no per-visitor retention.</li>
        <li><strong>Server / hosting logs</strong>: short-term, per the retention defaults of Vercel and Neon.</li>
        <li><strong>Form submissions (suggest, contact)</strong>: until acted on or deemed no longer relevant; typically not longer than 24 months unless they relate to an ongoing matter.</li>
        <li><strong>Vendor account</strong>: for the life of the account.</li>
        <li><strong>Legal-acceptance audit trail</strong>: for the life of the account plus up to 6 years after closure, to evidence consent in case of dispute.</li>
        <li><strong>Audit logs of admin actions</strong>: 6 years.</li>
      </ul>

      <h2 className={h2}>4. Who we share your data with</h2>
      <p>We do not sell your personal data. We share it only with the processors needed to operate the Directory:</p>
      <ul className={ul}>
        <li><strong>Clerk, Inc.</strong> &mdash; authentication for vendor and admin accounts.</li>
        <li><strong>Vercel Inc.</strong> &mdash; hosting and serverless compute.</li>
        <li><strong>Neon, Inc.</strong> &mdash; managed Postgres database (region: Frankfurt, eu-central-1).</li>
        <li><strong>Vercel Blob</strong> &mdash; file storage for vendor logos and screenshots.</li>
        <li><strong>Resend</strong> &mdash; transactional email delivery (visitor-to-vendor forwarding, system notifications).</li>
        <li><strong>Plausible Analytics</strong> &mdash; aggregate, cookie-less analytics.</li>
        <li><strong>Sentry</strong> &mdash; error reporting and stack traces, used to debug failures.</li>
        <li><strong>Cloudflare</strong> &mdash; DNS and edge proxy in front of the site.</li>
      </ul>
      <p>
        We may also disclose personal data: (i) to professional advisers
        (lawyers, auditors); (ii) to comply with a lawful request, court order,
        or applicable law; (iii) to protect our rights, property, safety, or
        the rights, property, and safety of others; (iv) in connection with a
        merger, acquisition, financing, or sale of all or substantially all of
        our assets, in which case we will notify affected users.
      </p>

      <h2 className={h2}>5. International transfers</h2>
      <p>
        Your data may be processed outside the country in which you are
        located, including in the European Union, the United Kingdom, the
        United States, and the United Arab Emirates, depending on the processor.
        Where required, we rely on standard contractual clauses or equivalent
        safeguards offered by the relevant processor.
      </p>

      <h2 className={h2}>6. Security</h2>
      <p>
        We use HTTPS everywhere; HTTP Strict Transport Security; PKCE on OAuth;
        CSRF protection on forms; rate limiting on sensitive endpoints;
        server-side sanitisation of vendor-submitted rich text; per-role
        access control (Visitor / Vendor / Admin); and audit logging of admin
        actions. Admin accounts require two-factor authentication. No system is
        ever fully secure; we cannot guarantee absolute security and ask that
        you use a strong password (or LinkedIn account) and notify us promptly
        if you suspect compromise of your account at{" "}
        <strong>team@allinfratech.com</strong>.
      </p>

      <h2 className={h2}>7. Your rights</h2>
      <p>Subject to applicable law, you may have the right to:</p>
      <ul className={ul}>
        <li>Access the personal data we hold about you.</li>
        <li>Correct inaccurate personal data.</li>
        <li>Request deletion of your personal data (subject to retention obligations and our need to retain audit records as evidence).</li>
        <li>Restrict or object to certain processing.</li>
        <li>Receive your personal data in a portable format.</li>
        <li>Withdraw consent where consent is the basis for processing (without affecting prior lawful processing).</li>
        <li>Lodge a complaint with the data-protection authority of your jurisdiction.</li>
      </ul>
      <p>
        To exercise any of these rights, email{" "}
        <strong>team@allinfratech.com</strong>. We will respond within the
        period required by applicable law (typically 30 days).
      </p>

      <h2 className={h2}>8. Cookies and similar technologies</h2>
      <p>
        See our{" "}
        <a href="/legal/cookies" className="bloom-text underline-offset-4 hover:underline">Cookie Policy</a>
        {" "}for details. In short: visitors browsing the public Directory
        encounter no cookies. Authenticated users (Vendors, Admins) receive
        first-party, HTTP-only, route-scoped session cookies needed to keep
        them signed in.
      </p>

      <h2 className={h2}>9. Children</h2>
      <p>
        AllInfratech is not directed at children under 16 and we do not
        knowingly collect personal data from them. If you believe a child has
        provided personal data to us, contact{" "}
        <strong>team@allinfratech.com</strong> and we will delete it.
      </p>

      <h2 className={h2}>10. Changes to this Privacy Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. The version date
        at the top reflects the most recent change. For material changes
        affecting Vendors, we will notify the contact email on the account at
        least 14 days before the new version takes effect.
      </p>

      <h2 className={h2}>11. Contact</h2>
      <p>
        Resolute Management Consultancy &mdash; data controller. Contact:{" "}
        <strong>team@allinfratech.com</strong>.
      </p>
    </LegalShell>
  );
}
