import type { Metadata } from "next";
import {
  DocumentLayout,
  type DocumentSection,
} from "@/components/site/document-layout";
import { TERMS_LAST_UPDATED } from "@/lib/legal/terms-version";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How AllInfratech collects, uses, and protects personal data.",
  alternates: { canonical: "/legal/privacy" },
};

const ul = "list-disc space-y-2 pl-6";

const sections: DocumentSection[] = [
  {
    id: "who-we-are",
    label: "Who we are",
    content: (
      <p>
        This Privacy Policy explains how Resolute Management Consultancy
        (&ldquo;Resolute&rdquo;, &ldquo;we&rdquo;) collects, uses, and protects
        personal data in connection with AllInfratech (the
        &ldquo;Directory&rdquo;), available at{" "}
        <strong>allinfratech.com</strong>. We are the controller of the personal
        data described below and are contactable at{" "}
        <strong>team@allinfratech.com</strong>.
      </p>
    ),
  },
  {
    id: "data-we-collect",
    label: "Data we collect",
    content: (
      <>
        <p>
          <strong>(a) Visitors</strong> (anyone browsing the site)
        </p>
        <ul className={ul}>
          <li>
            <strong>Aggregate analytics</strong> via a privacy-friendly,
            cookie-less analytics provider. We see aggregate counts (page views,
            referrers, country, device type) &mdash; not individual visitors.
          </li>
          <li>
            <strong>Server logs</strong> generated by our hosting provider. These
            contain IP address, request path, status code, user-agent, and
            timestamps, retained for a short period for security and debugging.
          </li>
          <li>
            <strong>Form submissions</strong> if you use the &ldquo;Contact this
            vendor&rdquo; form. We collect the data you enter (typically name,
            email, message) and the IP address for rate-limiting and
            abuse-prevention.
          </li>
        </ul>
        <p>No advertising cookies, no cross-site trackers, no fingerprinting.</p>

        <p>
          <strong>(b) Vendors</strong> (signed-in users managing a listing)
        </p>
        <ul className={ul}>
          <li>
            <strong>Account profile</strong> when you sign in via LinkedIn OAuth:
            your name, email address, LinkedIn profile URL, and a stable user
            identifier issued by our authentication provider. We do not see your
            LinkedIn password.
          </li>
          <li>
            <strong>Vendor record</strong>: the company you represent, your role,
            the listing(s) you manage, and company-related fields you submit
            through the dashboard.
          </li>
          <li>
            <strong>Legal-acceptance audit trail</strong>: when you accept these
            terms (or a future update), we record the version accepted,
            timestamp, IP address, and user-agent string.
          </li>
          <li>
            <strong>Activity</strong>: records of submissions, edits, and
            dashboard actions retained as audit logs.
          </li>
          <li>
            <strong>Inbound messages</strong>: messages sent to you by visitors
            via the contact form are stored briefly for moderation and forwarded
            to the email address on your account.
          </li>
        </ul>

        <p>
          <strong>(c) Administrators</strong> (Resolute employees and
          contractors)
        </p>
        <p>Account profile (name, work email), audit log of admin actions.</p>
      </>
    ),
  },
  {
    id: "why-we-use-your-data",
    label: "Why we use your data",
    content: (
      <>
        <p>
          We rely on the following legal bases under applicable data-protection
          law (including the UAE Personal Data Protection Law and the EU/UK GDPR
          where it applies):
        </p>
        <ul className={ul}>
          <li>
            <strong>Contract</strong> &mdash; to operate vendor accounts and
            provide the dashboard.
          </li>
          <li>
            <strong>Legitimate interests</strong> &mdash; to operate, secure, and
            improve the Directory; prevent abuse; maintain audit logs; forward
            visitor messages to vendors; keep aggregate analytics.
          </li>
          <li>
            <strong>Legal obligation</strong> &mdash; to retain records we are
            required to keep and respond to lawful requests.
          </li>
          <li>
            <strong>Consent</strong> &mdash; where you have actively opted in
            (for example, accepting terms during onboarding).
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "retention",
    label: "How long we keep your data",
    content: (
      <ul className={ul}>
        <li>
          <strong>Visitor analytics</strong>: aggregate data only; no per-visitor
          retention.
        </li>
        <li>
          <strong>Server logs</strong>: short-term, per the defaults of our
          hosting provider.
        </li>
        <li>
          <strong>Contact-form submissions</strong>: until acted on or no longer
          relevant; typically not longer than 24&nbsp;months.
        </li>
        <li>
          <strong>Vendor account</strong>: for the life of the account.
        </li>
        <li>
          <strong>Legal-acceptance audit trail</strong>: for the life of the
          account plus a reasonable period thereafter to evidence consent in case
          of dispute.
        </li>
        <li>
          <strong>Audit logs</strong>: for as long as we have a legitimate
          interest in retaining them.
        </li>
      </ul>
    ),
  },
  {
    id: "data-sharing",
    label: "Who we share your data with",
    content: (
      <>
        <p>
          We do not sell your personal data. We share it only with the categories
          of processor needed to operate the Directory:
        </p>
        <ul className={ul}>
          <li>
            <strong>Authentication provider</strong> &mdash; vendor and admin
            sign-in.
          </li>
          <li>
            <strong>Hosting and compute provider</strong> &mdash; serving the
            site and running server-side code.
          </li>
          <li>
            <strong>Database provider</strong> &mdash; managed Postgres storage
            (EU region).
          </li>
          <li>
            <strong>File-storage provider</strong> &mdash; vendor logos and
            screenshots.
          </li>
          <li>
            <strong>Email delivery service</strong> &mdash; transactional email
            (visitor-to-vendor forwarding, system notifications).
          </li>
          <li>
            <strong>Analytics provider</strong> &mdash; aggregate, cookie-less
            analytics.
          </li>
          <li>
            <strong>Error-reporting service</strong> &mdash; debugging failures.
          </li>
          <li>
            <strong>DNS and edge-proxy provider</strong> &mdash; routing and
            caching.
          </li>
        </ul>
        <p>
          We may also disclose personal data: (i)&nbsp;to professional advisers;
          (ii)&nbsp;to comply with a lawful request, court order, or applicable
          law; (iii)&nbsp;to protect rights, property, or safety; (iv)&nbsp;in
          connection with a merger, acquisition, or sale of substantially all of
          our assets, in which case we will notify affected users.
        </p>
      </>
    ),
  },
  {
    id: "international-transfers",
    label: "International transfers",
    content: (
      <p>
        Your data may be processed outside the country in which you are located,
        including in the European Union, the United Kingdom, the United States,
        and the United Arab Emirates, depending on the processor. Where required,
        we rely on standard contractual clauses or equivalent safeguards.
      </p>
    ),
  },
  {
    id: "security",
    label: "Security",
    content: (
      <p>
        We use HTTPS everywhere, HTTP Strict Transport Security, PKCE on OAuth,
        CSRF protection on forms, rate limiting on sensitive endpoints,
        server-side sanitisation of vendor-submitted rich text, per-role access
        control, and audit logging of administrative actions. No system is ever
        fully secure; we cannot guarantee absolute security and ask that you
        notify us promptly at <strong>team@allinfratech.com</strong> if you
        suspect compromise of your account.
      </p>
    ),
  },
  {
    id: "your-rights",
    label: "Your rights",
    content: (
      <>
        <p>Subject to applicable law, you may have the right to:</p>
        <ul className={ul}>
          <li>Access the personal data we hold about you.</li>
          <li>Correct inaccurate personal data.</li>
          <li>
            Request deletion (subject to retention obligations and our need to
            retain audit records as evidence).
          </li>
          <li>Restrict or object to certain processing.</li>
          <li>Receive your personal data in a portable format.</li>
          <li>Withdraw consent where consent is the basis for processing.</li>
          <li>
            Lodge a complaint with the data-protection authority of your
            jurisdiction.
          </li>
        </ul>
        <p>
          To exercise any of these rights, email{" "}
          <strong>team@allinfratech.com</strong>. We will respond within the
          period required by applicable law (typically 30&nbsp;days).
        </p>
      </>
    ),
  },
  {
    id: "cookies",
    label: "Cookies",
    content: (
      <p>
        See our{" "}
        <a
          href="/legal/cookies"
          className="bloom-text underline-offset-4 hover:underline"
        >
          Cookie Policy
        </a>{" "}
        for details. In short: visitors browsing the public Directory encounter
        no cookies. Authenticated users receive first-party, HTTP-only session
        cookies needed to keep them signed in.
      </p>
    ),
  },
  {
    id: "children",
    label: "Children",
    content: (
      <p>
        AllInfratech is not directed at children under 16 and we do not knowingly
        collect personal data from them. If you believe a child has provided
        personal data to us, contact <strong>team@allinfratech.com</strong> and
        we will delete it.
      </p>
    ),
  },
  {
    id: "changes",
    label: "Changes to this policy",
    content: (
      <p>
        We may update this Privacy Policy from time to time. The version date at
        the top reflects the most recent change. For material changes affecting
        vendors, we will notify the contact email on the account at least
        14&nbsp;days before the new version takes effect.
      </p>
    ),
  },
  {
    id: "contact",
    label: "Contact",
    content: (
      <p>
        Resolute Management Consultancy &mdash; data controller. Contact:{" "}
        <strong>team@allinfratech.com</strong>.
      </p>
    ),
  },
];

export default function PrivacyPage() {
  return (
    <DocumentLayout
      eyebrow="Legal"
      title="Privacy Policy"
      lastUpdated={TERMS_LAST_UPDATED}
      version="1.1"
      sections={sections}
    />
  );
}
